
#todo setup datasource initalization with h2 (to have a context initialize for test scope)
#todo add missing properties example jdbc dialect etc
#fixme configuration not valid
#spring:
#    datasource:
#        url=jdbc:mysql://localhost:3306/fooddB
#        username=root
#        password=
#        driver-class-name=com.mysql.cj.jdbc.Driver
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: HikariCorePool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select * from information_schema.tables limit 1